Repository initc3/HoneyBadgerMPC, pull requests merged in 2019-04, with the labels that each got.

#225 Parallelize test running
  pytest.ini
  setup.py
Labels: feature request

#228 Add share and share array inversion
  honeybadgermpc/mixins.py
  honeybadgermpc/mpc.py
  tests/test_mixins.py
  tests/test_mpc.py
Labels: feature request

#233 Implement Jubjub MPC application
  honeybadgermpc/elliptic_curve.py
  progs/jubjub.py
  tests/progs/test_jubjub.py
Labels: applications

#246 Refactor MPC to follow VIFF's data flow model
  honeybadgermpc/mixins.py
  honeybadgermpc/mpc.py
  progs/jubjub.py
  tests/progs/test_jubjub.py
  tests/test_mixins.py
  tests/test_mpc.py
Labels: code quality

#247 Implement equality operation for shares
  .ci/travis-script.sh
  honeybadgermpc/equality.py
  tests/progs/test_jubjub.py
  tests/test_equality.py
Labels: feature request

#256 removes leftover ideal functionality stuff
  honeybadgermpc/commonsubset.sol
  honeybadgermpc/commonsubset_blockchain.py
  honeybadgermpc/commonsubset_functionality.py
  honeybadgermpc/rand_batch.py
  honeybadgermpc/rand_functionality.py
  honeybadgermpc/rand_protocol.py
  honeybadgermpc/secretshare_functionality.py
  tests/test_commonsubset_functionality.py
  tests/test_rand_batch.py
  tests/test_rand_functionality.py
  tests/test_rand_protocol.py
  tests/test_secretshare_functionality.py
Labels: code quality

#276 Update apps/ to use new mixins
  apps/shuffle/butterfly_network.py
  apps/shuffle/powermixing.py
Labels: bug
